### ISSUE TITLE
Push sshlib to mavenCentral

### ISSUE THREAD

**Issue by ghost** [connectbot/trilead-ssh2#1]

**Comment by kruton** [comment]
It's on jcenter currently. I haven't looked into mavenCentral because it looked complicated.

**Comment by ghost** [comment]
Fair enough, but I don't even see it on jcenter. It's available from a personal repo at bintray, indeed, but not from mainline jcenter. Maybe it's just my miserable connectivity, will re-check tomorrow.

**Comment by kruton** [comment]
You're right. I'll work on getting it into jcenter and possibly mavenCentral.

**Comment by kruton** [comment]
I have put [sshlib on jcenter](https://bintray.com/bintray/jcenter?filterByPkgName=sshlib).

**Comment by ghost** [comment]
Thanks for the quick response!

**Comment by kruton** [comment]
It's also in Maven Central as well now.
