### ISSUE TITLE
Provide API for returning multiple server host keys

### ISSUE THREAD

**Issue by kruton** [connectbot/trilead-ssh2#11]
The current `ServerHostKeyVerifier` only allows you to confirm the selected host key, but the host may return several different possible algorithms. Allowing the API users to return all the matching keys for the given hostname and port combination lets any keys that match proceed. Otherwise a situation arises where either the library or the server starts supporting a new type of key and the user is told "server identification has changed!"

**Comment by xDragonZ** [comment]
Hello, after the port to sshlib, connectbot is hard to connect now. I have to attempt multiple times so that it can connect to the server without error. I tested very old version of connectbot it doesn't have this problem.

Is this problem related to this issue?
http://i.imgur.com/4tmGEFc.jpg

**Comment by kruton** [comment]
Are you using the latest git release? The more information you give, the better I can answer.

**Comment by xDragonZ** [comment]
Yes, latest git release, tested Google Play connectbot too.

It will be great if you can contact me at `5pa6m@notsharingmy.info` so that I can send you detailed info with sample server.

**Comment by kruton** [comment]
Fixed with 771687e2d5355ba0e491e410f98fde6b00fa9434
