### ISSUE TITLE
Support newer key exchange algorithms

### ISSUE THREAD

**Issue by SvenBunge** [connectbot/trilead-ssh2#27]
Newer / safer key exchange algorithms (KexAlgorithms) are not supported by sshlib.
(Unfortunately they are recomendet by sides like bettercrypto.org)

Please add support of `diffie-hellman-group-exchange-sha256`

**Comment by kruton** [comment]
That [already exists](https://github.com/connectbot/sshlib/blob/3fa5973b07705533ff320f9dc23b9e7a173fd453/sshlib/src/main/java/com/trilead/ssh2/transport/KexManager.java#L90) in the code base.
