### ISSUE TITLE
sshlib does not support UTF-8 in usernames and passwords

### ISSUE THREAD

**Issue by iiordanov** [connectbot/trilead-ssh2#41]
This is due to encoding being forced to "ISO-8859-1" in `sshlib/src/main/java/com/trilead/ssh2/packets/TypesWriter.java` with:

`b = v.getBytes("ISO-8859-1");`

**Comment by iiordanov** [comment]
PR to deal with the issue: https://github.com/connectbot/sshlib/pull/42

**Comment by kruton** [comment]
Fixed with #42
