### ISSUE TITLE
Support rsa-sha2-{256,512} HOSTKEY_ALGS

### ISSUE THREAD

**Issue by hvenev** [connectbot/trilead-ssh2#64]
rsa-sha2-512 and rsa-sha2-256 already seem to be supported as public key algorithms, but not for host authentication.

**Comment by iiordanov** [comment]
I made a PR that fixes this. Tested on my local test systems. https://github.com/connectbot/sshlib/pull/72

**Comment by kruton** [comment]
Fixed with #72
