### ISSUE TITLE
Initializing KnownHosts only adds host keys for ssh-rsa and ssh-dss

### ISSUE THREAD

**Issue by rvmiller89** [connectbot/trilead-ssh2#65]
We are using `ServerHostKeyVerifier` and initializing `KnownHosts` with a file, e.g. `~/.ssh/known_hosts`.

However we are finding that verifying known hosts doesn't seem to work for `ssh-ed25519` host key verification, and reading through `KnownHosts`'s `initialize` method, I'm wondering if the problem might be https://github.com/connectbot/sshlib/blob/master/sshlib/src/main/java/com/trilead/ssh2/KnownHosts.java#L439 since it only seems to `addHostkey` for `ssh-rsa` or `ssh-dss`.

Are there any plans to add support for host key verification for other types of host keys?

**Comment by kruton** [comment]
There are currently no tests for this section of code and I don't use it for ConnectBot, so it's been neglected. If anyone wants to fix this part, it would be appreciated.

**Comment by rvmiller89** [comment]
Thanks @kruton, I have opened PR https://github.com/connectbot/sshlib/pull/73 if you are able to take a look.
